name: projetd
recipe: laravel

compose:
  - docker-compose.yml

config:
  php: '7.3'
  webroot: public
  xdebug: false
  via: nginx:1.14
  database: mariadb:10.3
  cache: redis:5
services:
  pma:
    type: phpmyadmin:4.7
    overrides:
      environment:
        PMA_HOST: database
  node:
    type: node
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php
    build_as_root:
      - apt-get update
tooling:
  npm:
    service: node
  yarn:
    service: node
  build:
    service: database
    description: Create phpunit database
    cmd:
      - mysql -u root -e "CREATE DATABASE IF NOT EXISTS phpunit;"
      - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '*';"
      - echo 'Create successfully !'
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  redis-cli:
    service: cache
proxy:
  pma:
    - pma-projetd.lndo.site
  mailhog:
    - mailhog-projetd.lndo.site
